#!/bin/bash
#Change the vlan parameter to the correct interface
iptables -A INPUT -p tcp -i vlan290 --dport 40000:60000 -j DROP
masscan -c masscan.conf > output
iptables -F
egrep "open port (80|3306)" output | wc
egrep Apache2\|MySQL output | wc
